# version : API版本目前支持 2.0.1
# url填写jumpserver站点地址
# coco填写ssh域名
jumpserver:
  version: 2.0.1
  url: https://jumpserver.opscloud.top
  coco: oc.opscloud.top
  admin:
    username: admin
    password: admin