# Macbook 安装ansible
# brew install ansible [or] brew upgrade ansible
# 当前最新版本为 ansible 2.9.6_1

# https://docs.ansible.com/ansible/latest/reference_appendices/config.html
# ansible.cfg
# 忽略主机文件中`-`字符警告
# force_valid_group_names = ignore
# 禁用警告信息
# deprecation_warnings = False

# inventoryPath: ${dataPath}/inventory
# scriptPath: ${dataPath}/script
# playbookPath: ${dataPath}/playbook
# privateKey: ${dataPath}/private_key/id_rsa
ansible:
  version: 2.9.6
  bin: /usr/local/bin/ansible
  dataPath: ${HOME}/Documents/workspace/opscloud-data/ansible
  playbookBin: /usr/local/bin/ansible-playbook
  logPath: ${HOME}/Documents/workspace/opscloud-data/log/ansible
